---
- name: "Prepare for STF functional tests"
  hosts: jumphost
  tasks:
    - name: "Log into OCP"
      ansible.builtin.shell:
        cmd: |
          oc login -u kubeadmin -p "$(cat /opt/ci/shiftstack-ci/clusters/{{ ocp_cluster_name }}/auth/kubeadmin-password)"
        environment:
          PATH: "{{ ansible_env.PATH }}:{{ ansible_env.HOME }}/.local/bin/:/usr/local/bin/"
      ignore_errors: true
      changed_when: false

- import_playbook: '{{ playbook_dir }}/../feature-verification-tests/stf_functional_tests.yml'
