#!usr/bin/env ansible-playbook
---
- name: "Add symlink for podman->docker so we don't have to change the commands in OSP13"
  hosts: overcloud_nodes
  become: true
  tags:
    - OSP13
  tasks:
    - file:
        src: /usr/bin/docker
        dest: /usr/bin/podman
        owner: root
        group: wheel
        state: link

- name: "Set up defaults"
  hosts: overcloud_nodes
  tags: always
  tasks:
    - include_vars:
        file: defaults/main.yml
        name: play_vars

    - set_fact: "{{item.key}}={{item.value}}"
      loop: "{{ play_vars|dict2items}}"

- name: "Set up defaults"
  hosts: overcloud_nodes
  tags: always
  tasks:
    - include_vars:
        file: defaults/main.yml
        name: play_vars

    - set_fact: "{{item.key}}={{item.value}}"
      loop: "{{ play_vars|dict2items}}"

- name: "Check that collectd is running and generating any metrics"
  hosts: overcloud_nodes
  ignore_errors: true
  become: true
  tags:
    - collectd-write-qdr-edge-only
    - collectd-write-qdr-mesh
    - enable-stf
  tasks:
    - import_tasks: tasks/test_collectd.yml

- name: "Check that metrics_qdr container is running and receiving ANY messages."
  hosts: overcloud_nodes
  ignore_errors: true
  become: true
  tags:
    - collectd-write-qdr-edge-only
    - collectd-write-qdr-mesh
    - ceilometer-write-qdr-edge-only
    - ceilometer-write-qdr-mesh
    - enable-stf
  tasks:
    - import_tasks: tasks/test_qdr.yml
