---
- name: "Check that collectd is running and generating any metrics"
  hosts: overcloud_nodes
  ignore_errors: true
  become: true
  tasks:
    - name: "Import the client_side tests to load default vars"
      import_role:
        name: client_side_tests
      tags:
        - always
    - name: "Update container_bin var"
      tags:
        - always
      block:
        - name: "Check for podman executable"
          stat:
            path: "/usr/bin/podman"
          register: st_pod
        - name: "Set container_bin=docker when podman isn't there"
          set_fact:
            container_bin: docker
          when: not st_pod.stat.exists

    - name: "Run collectd tests"
      import_role:
        name: client_side_tests
        tasks_from: test_collectd
      tags:
        - custom-stf-ceph
        - custom-stf-ceph-osp13
        - stf-connectors-osp13
        - stf-connectors-osp13-ffu
        - gnocchi-connectors-swift

    - name: "Run metrics_qdr tests"
      import_role:
        name: client_side_tests
        tasks_from: test_qdr
      tags:
        - custom-stf-ceph
        - custom-stf-ceph-osp13
        - stf-connectors-osp13
        - stf-connectors-osp13-ffu
        - gnocchi-connectors-swift

- name: "Run e2e tests"
  hosts: undercloud-0
  ignore_errors: true
  become: true
  become_method: sudo
  become_user: root
  tasks:
    - name: "Run collectd Prometheus queries"
      import_role:
        name: client_side_tests
        tasks_from: test_e2e
      tags:
        - custom-stf-ceph
        - stf-connectors-osp13-ffu
        - gnocchi-connectors-swift
