---
- name: "Add symlink for podman->docker so we don't have to change the commands in OSP13"
  hosts: overcloud_nodes
  become: true
  tags:
    - OSP13
  tasks:
    - file:
        src: /usr/bin/docker
        dest: /usr/bin/podman
        owner: root
        group: wheel
        state: link

- name: "Check that collectd is running and generating any metrics"
  hosts: overcloud_nodes
  ignore_errors: true
  become: true
  tasks:
    - import_role: name="{{ playbook_dir }}"
    - name: "Run collectd tests"
      import_tasks: tasks/test_collectd.yml
      tags:
        - collectd-write-qdr-edge-only
        - collectd-write-qdr-mesh
        - enable-stf
    - name: "Run metrics_qdr tests"
      import_tasks: tasks/test_qdr.yml
      tags:
        - collectd-write-qdr-edge-only
        - collectd-write-qdr-mesh
        - ceilometer-write-qdr-edge-only
        - ceilometer-write-qdr-mesh
        - enable-stf
