---
# Assuming we've already logged in...
# Following procedure on https://infrawatch.github.io/documentation/#high-availability_assembly-advanced-features
# Assuming we're in teh right project already...

- name: "Add highAvailability.enabled: true to the spec section"
  ansible.builtin.shell:
    cmd: |
      oc patch stf/default --type merge -p '{"spec":{"highAvailability":{"enabled": true}}}'
  changed_when: false
  register: cmd_output
  failed_when: cmd_output.rc != 0


- name: "Show the command output"
  ansible.builtin.debug:
    var: cmd_output


- name: "Wait 3 minutes to make sure all HA pods are up and running"
  ansible.builtin.pause:
    minutes: 3


- name: "Verify that AMQP Interconnect shows two containers"
  ansible.builtin.shell:
    cmd: |
      oc get pods | grep default-interconnect| wc -l
  register: cmd_output
  failed_when: "cmd_output.stdout|int !=2"
  changed_when: fals

- name: "Show the command output"
  ansible.builtin.debug:
    var: cmd_outpute


- name: "Verify that Alert Manager  shows two containers"
  ansible.builtin.shell:
    cmd: |
      oc get pods | grep alertmanager| wc -l
  register: cmd_output
  failed_when: "cmd_output.stdout|int !=2"
  changed_when: false


- name: "Show the command output"
  ansible.builtin.debug:
    var: cmd_output


- name: "Verify that Prometheus shows two containers"
  ansible.builtin.shell:
    cmd: |
      oc get pods | grep prometheus-default| wc -l
  register: cmd_output
  failed_when: "cmd_output.stdout|int !=2"
  changed_when: false


- name: "Show the command output"
  ansible.builtin.debug:
    var: cmd_output



- name: "Verify that Ceilometer Events Smartgateway shows two containers"
  ansible.builtin.shell:
    cmd: |
      oc get pods | grep default-cloud1-ceil-event| wc -l
  register: cmd_output
  failed_when: "cmd_output.stdout|int !=2"
  changed_when: false


- name: "Show the command output"
  ansible.builtin.debug:
    var: cmd_output


- name: "Verify that Ceilometer Metrics  Smartgateway shows two containers"
  ansible.builtin.shell:
    cmd: |
      oc get pods | grep default-cloud1-ceil-meter| wc -l
  register: cmd_output
  failed_when: "cmd_output.stdout|int !=2"
  changed_when: false


- name: "Show the command output"
  ansible.builtin.debug:
    var: cmd_output


- name: "Verify that Collectd Events Smartgateway shows two containers"
  ansible.builtin.shell:
    cmd: |
      oc get pods | grep default-cloud1-coll-event| wc -l
  register: cmd_output
  failed_when: "cmd_output.stdout|int !=2"
  changed_when: false


- name: "Show the command output"
  ansible.builtin.debug:
    var: cmd_output


- name: "Verify that Collectd Metrics Smartgateway shows two containers"
  ansible.builtin.shell:
    cmd: |
      oc get pods | grep default-cloud1-coll-meter| wc -l
  register: cmd_output
  failed_when: "cmd_output.stdout|int !=2"
  changed_when: false


- name: "Show the command output"
  ansible.builtin.debug:
    var: cmd_output


- name: "Verify that Collectd Sensubility shows two containers"
  ansible.builtin.shell:
    cmd: |
      oc get pods | grep default-cloud1-sens-meter| wc -l
  register: cmd_output
  failed_when: "cmd_output.stdout|int !=2"
  changed_when: false


- name: "Show the command output"
  ansible.builtin.debug:
    var: cmd_output


- name: "Verify that ElasticSearch shows three containers"
  ansible.builtin.shell:
    cmd: |
      oc get pods | grep elasticsearch-es-default| wc -l
  register: cmd_output
  failed_when: "cmd_output.stdout|int !=3"
  changed_when: false


- name: "Show the command output"
  ansible.builtin.debug:
    var: cmd_output


- name: "Disbale HighAvailability after running test"
  ansible.builtin.shell:
    cmd: |
      oc patch stf/default --type merge -p '{"spec":{"highAvailability":{"enabled": false}}}'
  changed_when: false
  register: cmd_output
  failed_when: cmd_output.rc != 0


- name: "Show the command output"
  ansible.builtin.debug:
    var: cmd_output


- name: "Wait 3 minutes to make sure all HA pods are destroyed"
  ansible.builtin.pause:
    minutes: 3
