---
- name: "[Test] Check that collectd container is running."
  shell: |
    {{ container_bin }} ps | grep {{ collectd_container_name }}
  register: container_nodes
  failed_when: container_nodes.stdout_lines|length != 1

- name: "[Test] Check for a non-zero number of metrics from collectd"
  command: |
    {{ container_bin }} exec {{ collectd_container_name }} collectdctl -s /var/run/collectd-socket listval
  register: metrics
  failed_when: "metrics.stdout_lines|length == 0"

- name: "[Debug] Check for a non-zero number of metrics from collectd"
  debug:
     var: metrics

- name: "[Debug] Get the value of some metric from collectd"
  debug:
    var: metrics.stdout_lines[-1]

- name: "[Test] Get the value of some metric from collectd"
  command: |
    {{ container_bin }} exec {{ collectd_container_name }} collectdctl -s /var/run/collectd-socket getval {{ metrics.stdout_lines[-1] }}
  register: stat
  failed_when: not(stat.stdout_lines|length == 1)
