---
- name: "RHELOSP-60406"
  shell: |
    {{ container_bin }} ps | grep {{ collectd_container_name }}
  register: container_nodes
  failed_when: container_nodes.stdout_lines|length != 1

- name: "RHELOSP-60411"
  command: |
    {{ container_bin }} exec {{ collectd_container_name }} collectdctl -s /var/run/collectd-socket listval
  register: metrics
  failed_when: "metrics.stdout_lines|length == 0"

- name: "[Debug] Check for a non-zero number of metrics from collectd"
  debug:
     var: metrics

- name: "[Debug] Get the value of some metric from collectd"
  debug:
    var: metrics.stdout_lines[-20]

- name: "RHELOSP-69331"
  command: |
    {{ container_bin }} exec {{ collectd_container_name }} collectdctl -s /var/run/collectd-socket getval {{ metrics.stdout_lines[-20] }}
  register: stat
  failed_when: stat.stdout_lines|length == 0
