---
- name: "[Test] Check that collectd container is running."
  shell: |
    {{ container_bin }} ps | grep {{ collectd_container_name }}
  register: container_nodes
  failed_when: container_nodes.stdout_lines|length != 1

- name: "[Test] Check for a non-zero number of metrics from collectd"
  shell: |
    {{ container_bin }} exec {{ collectd_container_name }} collectdctl -s /var/run/collectd-socket listval | wc -l
  register: num_metrics
  failed_when: "not (num_metrics.stdout|int !=0 )"

- name: "[Debug] Check for a non-zero number of metrics from collectd"
  debug:
     var: num_metrics

- name: "[Setup] Get the value of some metric from collectd"
  shell: |
    {{ container_bin }} exec {{ collectd_container_name }} collectdctl -s /var/run/collectd-socket listval | tail -1
  register: met

- name: "[Debug] Get the value of some metric from collectd"
  debug:
    var: met

- name: "[Test] Get the value of some metric from collectd"
  shell: |
    {{ container_bin }} exec {{ collectd_container_name }} collectdctl -s /var/run/collectd-socket getval {{ met.stdout }}
  register: stat
  failed_when: not(stat.stdout_lines|length == 1)
