- name: "[Test] Run openstack metric query to check Prometheus scrape endpoints"
  ansible.builtin.shell:
    cmd: | 
      oc rsh openstackclient openstack metric query up --disable-rbac -c container -c instance -c value
  register: metric_query_result
  changed_when: false

- name: Check if query was successful
  ansible.builtin.debug:
    msg: "Metric query result: {{ metric_query_result.stdout }}"
  when: metric_query_result.rc == 0

- name: Fail if the query was unsuccessful
  ansible.builtin.fail:
    msg: "Failed to query metrics or no data returned."
  when: metric_query_result.rc != 0
