---
- name: Get Pod Instance "{{ common_pod_status_str }}"
  ansible.builtin.shell:
    cmd: |
      oc get pods -n "{{ common_pod_nspace }}" | grep "{{ item }}" | grep "{{ common_pod_status_str }}" | awk '{print $1;}'
  register: podinstance
  changed_when: false

- name: Check terminated pod
  ansible.builtin.shell:
    cmd: |
      oc get pod -n "{{ common_pod_nspace }} {{ podinstance.stdout }}"
  register: output
  changed_when: false
  failed_when:
    - output.rc != 0
    - podinstance.stdout == ""

