---
- name: "Verify logging projects, endpoints, credentials, nodes, pods, services, manifests and subscriptions"
  hosts: controller
  gather_facts: no
  ignore_errors: true
  environment:
    KUBECONFIG: "{{ cifmw_openshift_kubeconfig }}"
    PATH: "{{ cifmw_path }}"
  vars_files:
    - logging_test.yml
  tasks:
    - name: "Verify Pods Status"
      block:
        - name: "Run Pod Check"
          ansible.builtin.import_role:
            name: common
          vars:
            common_pod_test_id: "{{ item.test_id }}"
            common_pod_status_str: "{{ item.status }}"
            common_pod_nspace: "{{ item.namespace }}"
            common_pod_list: "{{ item.pod_list }}"
      rescue:
        - name: "Log Failure for Pod Check {{ item.test_id }}"
          ansible.builtin.debug:
            msg: "Pod check failed for namespace: {{ item.namespace }}"
      when: item is defined
      with_items: "{{ logging_pod_checks }}"
