---
- name: "Generate an access token for prometheus"
  ansible.builtin.shell:
    cmd: |
      oc create token stf-prometheus-reader
  register: prom_token_out
  changed_when: false

- name: "Show the prom_secret value"
  ansible.builtin.debug:
    var: prom_token_out | string

- name: "Get the prom URL"
  ansible.builtin.shell:
    cmd: |
      oc get route/default-prometheus-proxy -ojson | jq '.spec.host' | sed 's/"//g'
  register: prom_route
  changed_when: false

- name: "Show the prom_route value"
  ansible.builtin.debug:
    var: prom_route.stdout

- name: "Get the prom creds from the secret"
  ansible.builtin.set_fact:
    prom_token: "{{ prom_token_out.stdout }}"
    prom_url: "{{ prom_route.stdout }}"
