---
- name: "Get the default-prometheus-htpasswd secret"
  ansible.builtin.shell:
    cmd: |
      oc  get secret default-prometheus-htpasswd -ojson | jq '.data.auth, .data.password' |  sed 's/"//g'
  register: prom_secret
  changed_when: false

- name: "Show the prom_secret value"
  ansible.builtin.debug:
    var: prom_secret | string

- name: "Get the prom URL"
  ansible.builtin.shell:
    cmd: |
      oc get route/default-prometheus-proxy -ojson | jq '.spec.host' | sed 's/"//g'
  register: prom_route
  changed_when: false

- name: "Show the prom_route value"
  ansible.builtin.debug:
    var: prom_route.stdout

- name: "Get the prom creds from the secret"
  ansible.builtin.set_fact:
    prom_user_decoded: "{{ (prom_secret.stdout_lines[0] | b64decode) }}"
    prom_pass: "{{ prom_secret.stdout_lines[1] | b64decode }}"
    prom_url: "{{ prom_route.stdout }}"

- name: "Show the prom_user value"
  ansible.builtin.debug:
    var: prom_user

- name: "Fetch user"
  ansible.builtin.set_fact:
    prom_user: "{{ prom_user_decoded.split(':')[0] }}"
  when: prom_user_decoded is defined

- name: | 
    "RHELOSP-37759"
     Description: Query Prometheus for collectd_cpu_percent metrics and save the output into the file
  ansible.builtin.shell:
    cmd: >-
      /usr/bin/curl -k -u "{{ prom_user }}:{{ prom_pass }}" \
        -g https://{{ prom_url }}/api/v1/query? \
        --data-urlencode 'query=collectd_cpu_percent {plugin_instance="0"}[1m]' \
        --output /tmp/query_collectd_cpu_percent
  register: checkmyconf
  changed_when: false
  failed_when:
    - checkmyconf.rc !=0

- name: |
    "RHELOSP-57528"
     Description: Query Prometheus for ceph_ceph_bytes metrics and save the output into the file
  ansible.builtin.shell:
    cmd: >-
      /usr/bin/curl -k -u "{{ prom_user }}:{{ prom_pass }}" \
        -g https://{{ prom_url }}/api/v1/query? \
        --data-urlencode 'query=collectd_ceph_ceph_bytes {plugin_instance="ceph-osd.5"}[1m]' \
        --output /tmp/query_ceph_ceph_bytes
  register: checkmyconf
  changed_when: false
  failed_when:
    - checkmyconf.rc !=0

- name: | 
    "RHELOSP-57536"
     Description: Query Prometheus for collectd_load_longterm metrics and save the output into the file
  ansible.builtin.shell:
    cmd: >-
      /usr/bin/curl -k -u "{{ prom_user }}:{{ prom_pass }}" \
        -g https://{{ prom_url }}/api/v1/query? \
        --data-urlencode 'query=collectd_interface_if_packets_tx_total {type_instance="base"}[1m]' \
        --output /tmp/query_collectd_interface_tx_total
  register: checkmyconf
  changed_when: false
  failed_when:
    - checkmyconf.rc !=0

- name: |
    "RHELOSP-37762"
     Description: Query Prometheus for collectd_memory metrics and save the output into the file
  ansible.builtin.shell:
    cmd: >-
      /usr/bin/curl -k -u "{{ prom_user }}:{{ prom_pass }}" \
        -g https://{{ prom_url }}/api/v1/query? \
        --data-urlencode 'query=collectd_memory {plugin_instance="base"}[1m]' \
        --output /tmp/query_collectd_memory
  register: checkmyconf
  changed_when: false
  failed_when:
    - checkmyconf.rc !=0

- name: |
    "RHELOSP-117539"
     Description: Query Prometheus for collectd_load_longterm metrics and save the output into the file
  ansible.builtin.shell:
    cmd: >-
      /usr/bin/curl -k -u "{{ prom_user }}:{{ prom_pass }}" \
        -g https://{{ prom_url }}/api/v1/query? \
        --data-urlencode 'query=collectd_load_longterm {plugin_instance="base"}[1m]' \
        --output /tmp/query_load_longterm
  register: checkmyconf
  changed_when: false
  failed_when:
    - checkmyconf.rc !=0

- name: |
    "RHELOSP-37757"
     Description: Read content of query_ceph_ceph_bytes file and check that metrics are present
  ansible.builtin.command:
    cmd: >-
       egrep 'ceph' /tmp/query_ceph_ceph_bytes
  register: checkmyconf
  changed_when: false
  failed_when:
    - checkmyconf.rc != 0

- name: |
    "RHELOSP-37218"
     Description: Read content of query_collectd_interface_tx_total file and check that metrics are present
  ansible.builtin.shell:
    cmd: >-
       egrep 'controller-0|controller-1|controller-2|compute-0|compute-1|ceph-0' /tmp/query_collectd_interface_tx_total
  register: checkmyconf
  changed_when: false
  failed_when:
    - checkmyconf.rc != 0

- name: |
    "RHELOSP-37636"
     Description: Read content of query_collectd_cpu_percent file and check that metrics are present
  ansible.builtin.shell:
    cmd: >-
      egrep 'controller-0|controller-1|controller-2|compute-0|compute-1|ceph-0' /tmp/query_collectd_cpu_percent
  register: checkmyconf
  changed_when: false
  failed_when:
    - checkmyconf.rc != 0


- name: |
    "RHELOSP-37670"
     Description: Read content of query_collectd_memory file and check that metrics are present
  ansible.builtin.shell:
    cmd: >-
      egrep 'controller-0|controller-1|controller-2|compute-0|compute-1|ceph-0' /tmp/query_collectd_memory
  register: checkmyconf
  changed_when: false
  failed_when:
    - checkmyconf.rc != 0


- name: |
    "RHELOSP-37224"
     Description: Read content of query_load_longterm file and check that metrics are present
  ansible.builtin.shell:
    cmd: >-
      egrep 'controller-0|controller-1|controller-2|compute-0|compute-1|ceph-0' /tmp/query_load_longterm
  register: checkmyconf
  changed_when: false
  failed_when:
    - checkmyconf.rc != 0
